services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secondhand_et
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
